apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: lschulzes/auth-monorepo
      context: .
      docker:
        dockerfile: apps/auth/Dockerfile.dev.auth
      sync:
        manual:
          - src: 'apps/**/*.ts'
            dest: .
    - image: lschulzes/blog-monorepo
      context: .
      docker:
        dockerfile: apps/blog/Dockerfile.dev.blog
      sync:
        manual:
          - src: 'apps/**/*.ts'
            dest: .
    - image: lschulzes/client-monorepo
      context: .
      docker:
        dockerfile: apps/client/Dockerfile.dev.client
      sync:
        manual:
          - src: 'apps/**/*.tsx'
            dest: .
