apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: lschulzes/auth-monorepo
      context: .
      docker:
        dockerfile: Dockerfile.auth
      sync:
        manual:
          - src: 'apps/**/**/**/*.ts'
            dest: .
          - src: 'apps/**/**/*.ts'
            dest: .
    - image: lschulzes/blog-monorepo
      context: .
      docker:
        dockerfile: Dockerfile.blog
      sync:
        manual:
          - src: 'apps/**/**/**/*.ts'
            dest: .
          - src: 'apps/**/**/*.ts'
            dest: .
